"""Bootstrap script to initialise the IMDb movie trends repository structure."""

from __future__ import annotations

import sys
from pathlib import Path

from config import DATA_DIR, PROCESSED_DATA_DIR, RAW_DATA_DIR, REPORTS_DIR, ensure_directories


PROJECT_ROOT = Path(__file__).resolve().parent


DIRECTORIES = [
    DATA_DIR,
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    PROJECT_ROOT / "docs",
    PROJECT_ROOT / "docs" / "meeting_notes",
    PROJECT_ROOT / "notebooks",
    REPORTS_DIR,
    REPORTS_DIR / "figures",
    REPORTS_DIR / "phase1",
    PROJECT_ROOT / "src",
]


ESSENTIAL_FILES = {
    PROJECT_ROOT / "README.md": "# IMDb Movie Trends Analysis\n",
    PROJECT_ROOT / ".gitignore": "# Generated by setup_project.py\n",
}


def main() -> None:
    ensure_directories()
    for directory in DIRECTORIES:
        directory.mkdir(parents=True, exist_ok=True)

    for path, default_content in ESSENTIAL_FILES.items():
        if not path.exists():
            path.write_text(default_content, encoding="utf-8")

    print("Project scaffolding ensured. Review README.md for next steps.")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # pragma: no cover
        print(f"Setup failed: {exc}", file=sys.stderr)
        raise
